/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminDeploymentsRouteImport } from './routes/admin/deployments'
import { Route as AdminInvitationsRouteImport } from './routes/admin/invitations'
import { Route as AdminRsvpsRouteImport } from './routes/admin/rsvps'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ClientIndexRouteImport } from './routes/client/index'
import { Route as ClientRsvpRouteImport } from './routes/client/rsvp'
import { Route as ClientTemplatesRouteImport } from './routes/client/templates'
import { Route as ISlugRouteImport } from './routes/i.$slug'
import { Route as TemplatesSlugRouteImport } from './routes/templates.$slug'
import { Route as ClientBuilderSlugRouteImport } from './routes/client/builder.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeploymentsRoute = AdminDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRsvpsRoute = AdminRsvpsRouteImport.update({
  id: '/rsvps',
  path: '/rsvps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientRsvpRoute = ClientRsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => ClientRoute,
} as any)
const ClientTemplatesRoute = ClientTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ClientRoute,
} as any)
const ISlugRoute = ISlugRouteImport.update({
  id: '/i/$slug',
  path: '/i/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TemplatesRoute,
} as any)
const ClientBuilderSlugRoute = ClientBuilderSlugRouteImport.update({
  id: '/builder/$slug',
  path: '/builder/$slug',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/deployments': typeof AdminDeploymentsRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/rsvps': typeof AdminRsvpsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/rsvp': typeof ClientRsvpRoute
  '/client/templates': typeof ClientTemplatesRoute
  '/i/$slug': typeof ISlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/builder/$slug': typeof ClientBuilderSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/deployments': typeof AdminDeploymentsRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/rsvps': typeof AdminRsvpsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/rsvp': typeof ClientRsvpRoute
  '/client/templates': typeof ClientTemplatesRoute
  '/i/$slug': typeof ISlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/client/builder/$slug': typeof ClientBuilderSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/deployments': typeof AdminDeploymentsRoute
  '/admin/invitations': typeof AdminInvitationsRoute
  '/admin/rsvps': typeof AdminRsvpsRoute
  '/admin/users': typeof AdminUsersRoute
  '/client/rsvp': typeof ClientRsvpRoute
  '/client/templates': typeof ClientTemplatesRoute
  '/i/$slug': typeof ISlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/client/builder/$slug': typeof ClientBuilderSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/client'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/setup'
    | '/templates'
    | '/admin/analytics'
    | '/admin/deployments'
    | '/admin/invitations'
    | '/admin/rsvps'
    | '/admin/users'
    | '/client/rsvp'
    | '/client/templates'
    | '/i/$slug'
    | '/templates/$slug'
    | '/admin/'
    | '/client/'
    | '/client/builder/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/setup'
    | '/templates'
    | '/admin/analytics'
    | '/admin/deployments'
    | '/admin/invitations'
    | '/admin/rsvps'
    | '/admin/users'
    | '/client/rsvp'
    | '/client/templates'
    | '/i/$slug'
    | '/templates/$slug'
    | '/admin'
    | '/client'
    | '/client/builder/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/client'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/setup'
    | '/templates'
    | '/admin/analytics'
    | '/admin/deployments'
    | '/admin/invitations'
    | '/admin/rsvps'
    | '/admin/users'
    | '/client/rsvp'
    | '/client/templates'
    | '/i/$slug'
    | '/templates/$slug'
    | '/admin/'
    | '/client/'
    | '/client/builder/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  ISlugRoute: typeof ISlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deployments': {
      id: '/admin/deployments'
      path: '/deployments'
      fullPath: '/admin/deployments'
      preLoaderRoute: typeof AdminDeploymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invitations': {
      id: '/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rsvps': {
      id: '/admin/rsvps'
      path: '/rsvps'
      fullPath: '/admin/rsvps'
      preLoaderRoute: typeof AdminRsvpsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/rsvp': {
      id: '/client/rsvp'
      path: '/rsvp'
      fullPath: '/client/rsvp'
      preLoaderRoute: typeof ClientRsvpRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/templates': {
      id: '/client/templates'
      path: '/templates'
      fullPath: '/client/templates'
      preLoaderRoute: typeof ClientTemplatesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/i/$slug': {
      id: '/i/$slug'
      path: '/i/$slug'
      fullPath: '/i/$slug'
      preLoaderRoute: typeof ISlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/client/builder/$slug': {
      id: '/client/builder/$slug'
      path: '/builder/$slug'
      fullPath: '/client/builder/$slug'
      preLoaderRoute: typeof ClientBuilderSlugRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDeploymentsRoute: typeof AdminDeploymentsRoute
  AdminInvitationsRoute: typeof AdminInvitationsRoute
  AdminRsvpsRoute: typeof AdminRsvpsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDeploymentsRoute: AdminDeploymentsRoute,
  AdminInvitationsRoute: AdminInvitationsRoute,
  AdminRsvpsRoute: AdminRsvpsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientRsvpRoute: typeof ClientRsvpRoute
  ClientTemplatesRoute: typeof ClientTemplatesRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientBuilderSlugRoute: typeof ClientBuilderSlugRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientRsvpRoute: ClientRsvpRoute,
  ClientTemplatesRoute: ClientTemplatesRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientBuilderSlugRoute: ClientBuilderSlugRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface TemplatesRouteChildren {
  TemplatesSlugRoute: typeof TemplatesSlugRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesSlugRoute: TemplatesSlugRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  ISlugRoute: ISlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
